# Generated by Django 2.2.2 on 2019-06-26 19:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts_app.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=700)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_original', models.BooleanField(default=True)),
                ('has_parent', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=1)),
                ('reports', models.IntegerField(default=0)),
                ('commentfeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts_app.CommentFeed')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.Sub')),
                ('parent_comment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts_app.Comment')),
            ],
        ),
    ]
